# Use root/example as user/password credentials

# you need a recent version of Docker compose
version: '3.1'

# set TAG to specify docker image version
# set CONFIGDIR to path to config
# set SHOCKDIR for persistent Shock data store , e.g. /Users/Andi/Development/Shock
# set LOGDIR to path to local log dir
# set DOCKER_BINARY to the path of the docker client binary (Linux binary, not OSX/Windows)


services:

    # the SHOCK object store 
    shock:
        image: mgrast/shock
        depends_on:
          - mongo
        entrypoint:
          - /go/bin/shock-server
          - --conf
          - /shock-config/shock-server.cfg
        volumes:
          - ${CONFIGDIR}/Shock/shock-server.container.cfg:/shock-config/shock-server.cfg
          - ${LOGDIR}/shock:/var/log/shock
          - ${SHOCKDIR}/data:/usr/local/shock
        ports:
          - 7445:7445
          - 8083:80

    # web frontend for the shock browser
    shock-browser:
        image: mgrast/shock-browser:${TAG}
        depends_on:
          - shock
          - auth
        volumes:
          - ${CONFIGDIR}/ShockBrowser/config.js:/usr/share/nginx/html/js/config.js

    # local Oauth2 server for user, password and tokens
    auth:
        image: mgrast/authserver:${TAG}
        environment:
            MYSQL_HOST: db
            MYSQL_DATABASE: DemoAppUsers
            MYSQL_USER: authService
            MYSQL_PASSWORD: authServicePassword
        depends_on:
          - db
        volumes:
          - ${CONFIGDIR}/authServer/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
          - ${CONFIGDIR}/authServer/OAuthConfig.pm:/usr/local/apache2/htdocs/OAuthConfig.pm:ro
          - ${CONFIGDIR}/authServer/client.cgi:/usr/local/apache2/htdocs/cgi-bin/client.cgi:ro
        ports:
          - 8081:80

    # AWE resource manager
    awe-server:
        image: mgrast/awe:develop
        entrypoint:
          - /go/bin/awe-server
          - --conf=/awe-config/awe-server.cfg
        depends_on:
          - awe-mongo
          - auth
        ports:
          - 8001
          - 8081
        volumes:
          - ${CONFIGDIR}/awe/awe-server.conf:/awe-config/awe-server.cfg:ro
          - ${DATADIR}/awe:/mnt/data/awe/
          - ${LOGDIR}/awe/:/mnt/data/awe/logs


    # the AWE worker that will execute the workflow steps
    awe-worker:
        image: mgrast/awe-worker:develop
        # worker needs to wait for AWE-server to start up
        entrypoint:
          - ash
          - -c
          - 'sleep 30 ;
            /go/bin/awe-worker
            --name compose_worker-1
            --data=${DATADIR}/awe-worker/data
            --logs=/mnt/data/logs
            --workpath=${DATADIR}/awe-worker/work
            --serverurl=http://awe-server:8001
            --group=docker
            --supported_apps=*
            --auto_clean_dir=false
            --debuglevel=0'
        depends_on:
          - awe-server
        volumes:
          - /tmp:/tmp
          - ${CONFIGDIR}/AWE/awe-worker.cfg:/awe-config/awe-worker.cfg:ro
          - ${DATADIR}/awe-worker:${DATADIR}/awe-worker
          - ${LOGDIR}/awe-worker/:/mnt/data/logs
          # mount the binary we have downloaded with the init.sh command
          - ${DOCKER_BINARY}:/usr/local/bin/docker
          # mount the docker socker to allow container to execute docker commands (for CWL runner)
          - /var/run/docker.sock:/var/run/docker.sock

    # nginx integrates various containers and exposes required ports
    nginx:
        image: nginx
        depends_on:
          - shock
          - adminer
          - auth
          - awe-server
        ports:
          - 8001:8001
        volumes:
          - ${CONFIGDIR}/nginx/skyport-demo.conf:/etc/nginx/conf.d/skyport.conf:ro
          - ${CONFIGDIR}/nginx/index.html:/usr/share/nginx/html/index.html
          - ${CONFIGDIR}/nginx/bootstrap.min.css:/usr/share/nginx/html/bootstrap.min.css
          - ${CONFIGDIR}/nginx/skyportlogo.png:/usr/share/nginx/html/skyportlogo.png
          - ${CONFIGDIR}/nginx/drone.jpg:/usr/share/nginx/html/drone.jpg
          - ${LOGDIR}/nginx/:/var/log/nginx/

    adminer:
        image: adminer
        ports:
            - 8080:8080

    mongo:
        image: mongo
        ports:
          - 27017

    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: DemoAppUsers
            MYSQL_USER: authService
            MYSQL_PASSWORD: authServicePassword
        volumes:
          - /var/lib/mysql


    awe-mongo:
        image: mongo
        ports:
          - 27017



